### ISSUE TITLE
RuntimeError: The size of tensor a (66) must match the size of tensor b (67) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Billy4J** [swz30/MPRNet#14] opened 2021-03-08 07:08 UTC
```
===>Testing using weights:  ./pretrained_models/model_denoising.pth
  0%|          | 0/1 [00:00<?, ?it/s]D:\WorkTools\ProgramData\Anaconda3\envs\py36\lib\site-packages\torch\nn\functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
  0%|          | 0/1 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "E:/gitrestorys/denoising/MPRNet/Denoising/test_SIDD.py", line 65, in <module>
    restored_patch = model_restoration(noisy_patch)
  File "D:\WorkTools\ProgramData\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\WorkTools\ProgramData\Anaconda3\envs\py36\lib\site-packages\torch\nn\parallel\data_parallel.py", line 149, in forward
    return self.module(*inputs, **kwargs)
  File "D:\WorkTools\ProgramData\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\gitrestorys\denoising\MPRNet\Denoising\MPRNet.py", line 300, in forward
    res1_top = self.stage1_decoder(feat1_top)
  File "D:\WorkTools\ProgramData\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\gitrestorys\denoising\MPRNet\Denoising\MPRNet.py", line 145, in forward
    x = self.up32(dec3, self.skip_attn2(enc2))
  File "D:\WorkTools\ProgramData\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\gitrestorys\denoising\MPRNet\Denoising\MPRNet.py", line 183, in forward
    x = x + y
RuntimeError: The size of tensor a (66) must match the size of tensor b (67) at non-singleton dimension 2

Process finished with exit code -1
```
how to fix it

**Comment by swz30** [comment] 2021-03-08 07:38
Hi @Billy4J, 

If you are testing the denoising model on your own images, please use the [demo.py](https://github.com/swz30/MPRNet/blob/main/demo.py).

``` 
python demo.py --task Denoising --input_dir ./samples/input/ --result_dir ./samples/output/
```

**Comment by House-Leo** [comment] 2021-03-11 04:15
> Hi @Billy4J,
> 
> If you are testing the denoising model on your own images, please use the [demo.py](https://github.com/swz30/MPRNet/blob/main/demo.py). (There we have a block of code to handle images whose resolution is not a multiple of 8).
> 
> ```
> python demo.py --task Denoising --input_dir ./samples/input/ --result_dir ./samples/output/
> ```
When I run train.py for donoising, same problem has happened. 
`Traceback (most recent call last):
  File "train.py", line 142, in <module>
    restored = model_restoration(input_)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzj6850/HouseLee/MPRNet/Denoising/MPRNet.py", line 300, in forward
    res1_top = self.stage1_decoder(feat1_top)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzj6850/HouseLee/MPRNet/Denoising/MPRNet.py", line 145, in forward
    x = self.up32(dec3, self.skip_attn2(enc2))
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzj6850/HouseLee/MPRNet/Denoising/MPRNet.py", line 183, in forward
    x = x + y
RuntimeError: The size of tensor a (96) must match the size of tensor b (98) at non-singleton dimension 3
`

**Comment by House-Leo** [comment] 2021-03-11 04:18
When I run train.py for donoising, same problem has happened.
```
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    restored = model_restoration(input_)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzj6850/HouseLee/MPRNet/Denoising/MPRNet.py", line 300, in forward
    res1_top = self.stage1_decoder(feat1_top)
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzj6850/HouseLee/MPRNet/Denoising/MPRNet.py", line 145, in forward
    x = self.up32(dec3, self.skip_attn2(enc2))
  File "/public_files/software/envs/MPRNet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yzj6850/HouseLee/MPRNet/Denoising/MPRNet.py", line 183, in forward
    x = x + y
RuntimeError: The size of tensor a (96) must match the size of tensor b (98) at non-singleton dimension 3
```

**Comment by swz30** [comment] 2021-03-11 07:28
Hi @House-Leo 

What is the resolution of your validation images?

**Comment by adityac8** [comment] 2021-03-11 07:35
Hi @House-Leo 

The issue is fixed now. The validation patch size in `training.yml` should be a multiple of 8.
https://github.com/swz30/MPRNet/blob/51b58bb2ec803162e9053c1269b170009ee6f693/Denoising/training.yml#L26

Thanks

**Comment by House-Leo** [comment] 2021-03-11 07:40
> Hi @House-Leo
> 
> What is the resolution of your validation images?



> Hi @House-Leo
> 
> The issue is fixed now. The validation patch size in `training.yml` should be a multiple of 8.
> https://github.com/swz30/MPRNet/blob/51b58bb2ec803162e9053c1269b170009ee6f693/Denoising/training.yml#L26
> 
> Thanks

I fix this little bug about an hour ago, the original setting was `VAL_PS: 196` .
Thank you for your answer!

**Closed** 2021-03-11 07:42 UTC
